//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.ColmedicaModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class chatbotDataNoTransactional
    {
        public int id { get; set; }
        public string user_name { get; set; }
        public string request_response { get; set; }
        public string session_id_client { get; set; }
        public string score { get; set; }
        public string intentName { get; set; }
        public string action_bot { get; set; }
        public Nullable<System.DateTime> date_transaction { get; set; }
        public string language { get; set; }
        public string json_dialogflow { get; set; }
        public string contextLife { get; set; }
        public string ipAddress { get; set; }
        public string deviceFamily { get; set; }
        public string osClient { get; set; }
        public string osVersion { get; set; }
        public string browserClient { get; set; }
        public Nullable<int> id_understanding { get; set; }
        public Nullable<int> id_intentList { get; set; }
    }
}
