//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.ColmedicaModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class cmTipoDocumento
    {
        public int id { get; set; }
        public string tipo_doc { get; set; }
        public string doc_label { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> orden { get; set; }
    }
}
