//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.ColmedicaModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ColmedicaContext : DbContext
    {
        public ColmedicaContext()
            : base("name=ColmedicaContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<chatbotData> chatbotData { get; set; }
        public virtual DbSet<intentCategory> intentCategory { get; set; }
        public virtual DbSet<intentList> intentList { get; set; }
        public virtual DbSet<intentUnderstanding> intentUnderstanding { get; set; }
        public virtual DbSet<tempContratos> tempContratos { get; set; }
        public virtual DbSet<tempEspecialidades> tempEspecialidades { get; set; }
        public virtual DbSet<tempInfoAgendamiento> tempInfoAgendamiento { get; set; }
        public virtual DbSet<userVisits> userVisits { get; set; }
        public virtual DbSet<whiteListIntent> whiteListIntent { get; set; }
        public virtual DbSet<chatbotDataNoTransactional> chatbotDataNoTransactional { get; set; }
        public virtual DbSet<cmTipoDocumento> cmTipoDocumento { get; set; }
        public virtual DbSet<tempCita> tempCita { get; set; }
        public virtual DbSet<logErrorPeticion> logErrorPeticion { get; set; }
        public virtual DbSet<log_petitions> log_petitions { get; set; }
        public virtual DbSet<tempBeneficiarios> tempBeneficiarios { get; set; }
        public virtual DbSet<tempCiudades> tempCiudades { get; set; }
    }
}
