//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.ColmedicaModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class intentList
    {
        public int id { get; set; }
        public string intent_name { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> id_intent_category { get; set; }
        public string process_type { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string intent_label { get; set; }
    }
}
