//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.ColmedicaModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class log_petitions
    {
        public int id { get; set; }
        public string action { get; set; }
        public string parameters { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    }
}
