//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.ColmedicaModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tempContratosFactura
    {
        public int id { get; set; }
        public string contrato { get; set; }
        public string numeroContrato { get; set; }
        public string saldo { get; set; }
        public string idConv { get; set; }
        public Nullable<System.DateTime> fechaRegistro { get; set; }
    }
}
