//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.ColmedicaModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tempAuth
    {
        public int id { get; set; }
        public string idConv { get; set; }
        public string token { get; set; }
        public string numDoc { get; set; }
        public string tipoDoc { get; set; }
        public string otp { get; set; }
    }
}
