//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.ColmedicaModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tempBeneficiarios
    {
        public int id { get; set; }
        public Nullable<int> ciudadResidencia { get; set; }
        public Nullable<int> colectivo { get; set; }
        public string descripcionPlan { get; set; }
        public Nullable<int> idUsuario { get; set; }
        public string nombre { get; set; }
        public Nullable<int> numeroContrato { get; set; }
        public string numeroIdentificacion { get; set; }
        public string parentesco { get; set; }
        public string sexo { get; set; }
        public string telefonoCelular { get; set; }
        public string telefonoResidencia { get; set; }
        public string tipoIdentificacion { get; set; }
        public string idConv { get; set; }
    }
}
